spring.application.name=partido-politico-mvcc

# Configuración de Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/partido_politico_db
spring.datasource.username=postgres
spring.datasource.password=Futurelo#2007
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Configuración de Correo (Simulado / Desarrollo)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=jpuello169@gmail.com
spring.mail.password=ieoeeohtrvjyocai
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true